# Site
title = "启程"
subtitle = ""
description = ""
author = ""

# URL
url = ""
permalink " :year/:month/:day/:title.html"

# Directory
source_dir = "source/_posts"
public_dir = "public"
tag_dir = "tags"
category_dir = "categories"

# Pagination
per_page = 10
pagination_dir = "page"

# Theme
theme_dir = "themes"
theme = "unnamed"