# Site
title = "启程"
subtitle = ""
description = ""
author = ""
rss = "/atom.xml"

# URL
url = ""
root = "/"
permalink = ":year/:month/:day/:title.html"

# Directory
source_dir = "source/_posts"
public_dir = "public"
tag_dir = "tags"
category_dir = "categories"
archive_dir = "archives"

# Category & Tag
default_category = "default"

# Writing
titlecase = false # Transform title into titlecase
render_drafts = false
relative_link = false

# 
external_link = true

# Pagination
per_page = 10
pagination_dir = "page"

# Theme
theme_dir = "themes"
theme = "landscape"