# Content
excerpt_link = "Read More"

fancybox = true

# Sidebar
sidebar = "right"

# Favicon
favicon = "favicon.ico"

# Menu
[[menu]]
title = "Home"
url = "/"
[[menu]]
title = "Archives"
url = "/archives"
[[menu]]
title = "GitHub"
url = "https://github.com"
