# Content
excerpt_link = "Read More"

# Sidebar
sidebar = "right"

# Favicon
favicon = "/favicon.ico"

# Menu
[menu]
    [menu.home]
    title = "Home"
    url = "/"
    [menu.github]
    title = "GitHub"
    url = "https://github.com"
